menu:
  主页: /
  档案: /archives

widgets:
- search
- category
- tag

excerpt_link: 阅读全文

twitter:
  username: herosea27
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
